mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
   
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create/',views.create, name='create'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
        )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def test_was_published_recently_with_old_question(self):
        """
        was_published_recently() returns False for questions whose pub_date
        is older than 1 day.
        """
        time = timezone.now() - datetime.timedelta(days=1, seconds=1)
        old_question = Question(pub_date=time)
        self.assertIs(old_question.was_published_recently(), False)

    def test_was_published_recently_with_recent_question(self):
        """
        was_published_recently() returns True for questions whose pub_date
        is within the last day.
        """
        time = timezone.now() - datetime.timedelta(hours=23, minutes=59, seconds=59)
        recent_question = Question(pub_date=time)
        self.assertIs(recent_question.was_published_recently(), True)
    


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        

polls/views.py
from django.http import HttpResponse
from django.http import  HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.utils import timezone

from django.shortcuts import get_object_or_404, render
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:20]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def get_queryset(self):
    """
    Return the last five published questions (not including those set to be
    published in the future).
    """
    return Question.objects.filter(
    pub_date__lte=timezone.now()
    ).order_by('-pub_date')[:20]

def create(request):
    
    context = {}
    if request.method == "POST":
        question = Question.objects.create(question_text=request.POST['question_name'],pub_date=request.POST['pub_date'])
        Choice.objects.create(question=question,choice_text = request.POST['choice3'],votes = 0)
        Choice.objects.create(question=question,choice_text = request.POST['choice1'],votes = 0)
        Choice.objects.create(question=question,choice_text = request.POST['choice2'],votes = 0)
         
        return redirect('/polls/')

    return render(request,'create.html',context)

polls/templates/create.html
{% load static %}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body{
            background-color:rgb(38, 76, 116);
        }
        </style>
    
</head>
<body>

<form action="/polls/create/" method="post">
    {%csrf_token%}
    <div style="color:aliceblue; margin: 2rem;">
        <h2>Create Question</h2>
    </div>
    <div style="display:inline-block; justify-content:space-evenly;">
        <div class="card">
           
            <div class="card-body" style="padding-left: 5px;">
                <label for="question_name" style="color:rgb(7, 7, 0);">Question:</label>
            <input type="text" class="input-name" id="name" name="question_name" placeholder="Question" >
        </div>
        </div> 
        <div style="display:inline-block;">
        <div class="card">
        <div class="card-body" style="padding-left: 5px;">
            <label for="choice1" style="color:rgb(7, 7, 0)" >Choice 1:</label>
            <input type="text" class="input-choices" id="choice1" name="choice1" placeholder="Choice">
        </div>
    </div>
        <div class="card">
        <div class="card-body"  style="padding-left: 5px;">
            <label for="choice2" style="color:rgb(7, 7, 0)">Choice 2:</label>
            <input type="text" class="input-choices" id="choice2" name="choice2" placeholder="Choice">
        </div>
        </div>
        <div class="card">
            <div class="card-body" style="padding-left: 5px;" >
            <label for="choice3" style="color:rgb(8, 8, 0);">Choice 3:</label>
            <input type="text" class="input-choices" id="choice3" name="choice3" placeholder="Choice">
        </div>
        </div>  
    </div>
        <div class="card">
            <div class="card-body" style="padding-left: 5px;">
            <label for="pub_date" style="color:rgb(1, 1, 0)">Date:</label>
            <input type="text" class="input-choices" id="pub_date" name="pub_date" placeholder="Date">
        </div>
        </div>      
    </div>
    <button type="submit" class="btn btn-secondary" style="display:flexbox;">
        Submit
    </button>
</form>

</body>

polls/templates/polls/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Polls App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/style.css">

  </head>
  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/polls/detail.html
<!-- <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body{
            background-color:rgb(38, 76, 116);
        }
        </style>
    
</head>
<body>



<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <div class="card" style="width: 30rem; display: block;
    margin-left: auto;
    margin-right: auto; margin-top: 10rem; margin-bottom: 2rem;">
        <div class="card-body" style="background-color: rgb(183, 229, 250); box-shadow: 4px 4px 10px 2px rgba(46, 70, 103, 0.77);">
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
</div>
</div>
    <input class="btn btn-primary" type="submit" value="Vote" style="border-radius: 20px; display: block;
    margin-left: auto;
    margin-right: auto; width: 8rem; font-size:large; ">
    </form>

</body>

polls/templates/polls/index.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
    body{
        background-color:rgb(38, 76, 116);
    }
    </style>
</head>
<body>

<div class="whole" style="background-color: rgb(183, 229, 250); margin-left: 10vh; margin-right: 10vh; padding-top: 50px; padding-bottom: 50px; margin-top: 100px; border-radius: 40px; ">
<div class="d-flex flex-column justify-content-center align-items-center flex-column my-5">
    <h1 style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">Public Polls</h1>
    <span class="text-secondary">Choose a poll to vote!</span>
</div>

<div class="d-flex justify-content-center align-items-center flex-wrap my-5" style="padding-left: 0px;">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->

        <div class="card" style="width: 50vw; margin-bottom: 40px; padding-left: 20px; padding-right: 20px;">
            <div class="card-body">
              <h5 class="card-title"> <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li></h5>
              
            </div>
          </div>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
<div class="btn btn-outline-primary" style="background-color: aliceblue; display: block;
margin-left: auto;
margin-right: auto; width: 8rem;" >
    <a href="{% url 'polls:create'  %}">Create Poll</a>
</div>
</body>

polls/templates/polls/results.html
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body{
            background-color:rgb(38, 76, 116);
        }
        </style>
    
</head>
<body>
    <div class="card" style="width: 30rem; display: block;
    margin-left: auto;
    margin-right: auto; margin-top: 10rem; margin-bottom: 2rem;">
        <div class="card-body" style="background-color: rgb(183, 229, 250); box-shadow: 4px 4px 10px 2px rgba(46, 70, 103, 0.77);">
<h1>{{ question.question_text }}</h1>
     

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
</div>
</div>

<div class="btn btn-outline-primary" style="background-color: aliceblue; display: block;
margin-left: auto;
margin-right: auto; width: 8rem;" >
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
</body>